### ISSUE TITLE
WebComponents

### ISSUE THREAD

**Issue by jamesadarich** [gruckion/learning#2]
Outcomes

- [x] what benefits do web components give over traditional frameworks e.g. React

Web components are independent of the UI framework. A webcomp can be re-used across various frameworks or with none at all.

- [x] what is shadow DOM and how does it work?

The shadow DOM allows you to encapsulate your web component and hide away the child content of your web component. This includes markup structure, styling and behavior.

- Shadow host: The regular DOM node that the shadow DOM is attached to.
- Shadow tree: The DOM tree inside the shadow DOM.
- Shadow boundary: the place where the shadow DOM ends, and the regular DOM begins.
- Shadow root: The root node of the shadow tree.
 
- [x] how would you theme a web component? e.g. set colour globally for all components

Using the <style> tag. The web component's style can be protected via the Shadow DOM. This prevents styling external to the web component leaking into the component. If the shadow DOM is in the "open" mode then it is also possible to modify it using JavaScript.

`let shadow = elementRef.attachShadow({mode: 'open'});`

to style `var style = document.createElement('style'); style.textContent = ""; shadow.appendChild(style);`

- [x] how can you use web components outside of visual elements?

Non-visual elements could be an ajax web component, specifying a url end point and takes the serialized data of a form when another submit component is clicked. Or meta data or anything else that could encapsulate functionality that goes into the head of the document.
Useful links:

https://github.com/ionic-team/stencil
https://www.webcomponents.org/
https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM
https://groups.google.com/a/dartlang.org/forum/#!topic/web-ui/8EC9I0hyZP4
https://msdn.microsoft.com/en-us/library/bb386520.aspx - reading

**Comment by gruckion** [comment]
https://www.webcomponents.org/

1. Custom Elements – APIs to define new HTML elements
2. Shadow DOM – Encapsulated DOM and styling, with composition
3. HTML Imports – Declarative methods of importing HTML documents into other documents
4. ~~HTML Templates, an HTML fragment is not rendered, but stored until it is instantiated via JavaScript~~ potentially removed / not being focused on

https://stenciljs.com/

1. Light weight framework for building web components
2. 100% follows web component standards
3. Works with popular front end frameworks (React, Angular, Ember, Vue..)
4. Works with TypeScript
5. stencil-router, stencil-state-tunnel(react context), stencil-redux to build large applications (without a front end framework).
